### ISSUE TITLE
Infografia librerías 

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/infografia-de-las-librerias-Heidi-19#2]
[Infografia Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Heidi-19/files/8211171/Infografia.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by OFELHER93** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
